/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessoNegadoRouteImport } from './routes/acesso-negado'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ConsentimentoRouteImport } from './routes/consentimento'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ExclusaoDeDadosRouteImport } from './routes/exclusao-de-dados'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as PainelRouteRouteImport } from './routes/painel/route'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PainelIndexRouteImport } from './routes/painel/index'
import { Route as PainelAdminRouteImport } from './routes/painel/admin'
import { Route as PainelCampanhasRouteImport } from './routes/painel/campanhas'
import { Route as PainelConfiguracoesRouteImport } from './routes/painel/configuracoes'
import { Route as PainelIntegracoesRouteImport } from './routes/painel/integracoes'
import { Route as PainelLeadsRouteImport } from './routes/painel/leads'
import { Route as PainelListasRouteImport } from './routes/painel/listas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoNegadoRoute = AcessoNegadoRouteImport.update({
  id: '/acesso-negado',
  path: '/acesso-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentimentoRoute = ConsentimentoRouteImport.update({
  id: '/consentimento',
  path: '/consentimento',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusaoDeDadosRoute = ExclusaoDeDadosRouteImport.update({
  id: '/exclusao-de-dados',
  path: '/exclusao-de-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRouteRoute = PainelRouteRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelAdminRoute = PainelAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelCampanhasRoute = PainelCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelIntegracoesRoute = PainelIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelLeadsRoute = PainelLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelListasRoute = PainelListasRouteImport.update({
  id: '/listas',
  path: '/listas',
  getParentRoute: () => PainelRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteRouteWithChildren
  '/acesso-negado': typeof AcessoNegadoRoute
  '/cadastro': typeof CadastroRoute
  '/consentimento': typeof ConsentimentoRoute
  '/cookies': typeof CookiesRoute
  '/entrar': typeof EntrarRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/manutencao': typeof ManutencaoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/status': typeof StatusRoute
  '/termos': typeof TermosRoute
  '/painel/admin': typeof PainelAdminRoute
  '/painel/campanhas': typeof PainelCampanhasRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/integracoes': typeof PainelIntegracoesRoute
  '/painel/leads': typeof PainelLeadsRoute
  '/painel/listas': typeof PainelListasRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/cadastro': typeof CadastroRoute
  '/consentimento': typeof ConsentimentoRoute
  '/cookies': typeof CookiesRoute
  '/entrar': typeof EntrarRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/manutencao': typeof ManutencaoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/status': typeof StatusRoute
  '/termos': typeof TermosRoute
  '/painel/admin': typeof PainelAdminRoute
  '/painel/campanhas': typeof PainelCampanhasRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/integracoes': typeof PainelIntegracoesRoute
  '/painel/leads': typeof PainelLeadsRoute
  '/painel/listas': typeof PainelListasRoute
  '/painel': typeof PainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteRouteWithChildren
  '/acesso-negado': typeof AcessoNegadoRoute
  '/cadastro': typeof CadastroRoute
  '/consentimento': typeof ConsentimentoRoute
  '/cookies': typeof CookiesRoute
  '/entrar': typeof EntrarRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/manutencao': typeof ManutencaoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/status': typeof StatusRoute
  '/termos': typeof TermosRoute
  '/painel/admin': typeof PainelAdminRoute
  '/painel/campanhas': typeof PainelCampanhasRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/integracoes': typeof PainelIntegracoesRoute
  '/painel/leads': typeof PainelLeadsRoute
  '/painel/listas': typeof PainelListasRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/painel'
    | '/acesso-negado'
    | '/cadastro'
    | '/consentimento'
    | '/cookies'
    | '/entrar'
    | '/exclusao-de-dados'
    | '/manutencao'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/status'
    | '/termos'
    | '/painel/admin'
    | '/painel/campanhas'
    | '/painel/configuracoes'
    | '/painel/integracoes'
    | '/painel/leads'
    | '/painel/listas'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-negado'
    | '/cadastro'
    | '/consentimento'
    | '/cookies'
    | '/entrar'
    | '/exclusao-de-dados'
    | '/manutencao'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/status'
    | '/termos'
    | '/painel/admin'
    | '/painel/campanhas'
    | '/painel/configuracoes'
    | '/painel/integracoes'
    | '/painel/leads'
    | '/painel/listas'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/painel'
    | '/acesso-negado'
    | '/cadastro'
    | '/consentimento'
    | '/cookies'
    | '/entrar'
    | '/exclusao-de-dados'
    | '/manutencao'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/status'
    | '/termos'
    | '/painel/admin'
    | '/painel/campanhas'
    | '/painel/configuracoes'
    | '/painel/integracoes'
    | '/painel/leads'
    | '/painel/listas'
    | '/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRouteRoute: typeof PainelRouteRouteWithChildren
  AcessoNegadoRoute: typeof AcessoNegadoRoute
  CadastroRoute: typeof CadastroRoute
  ConsentimentoRoute: typeof ConsentimentoRoute
  CookiesRoute: typeof CookiesRoute
  EntrarRoute: typeof EntrarRoute
  ExclusaoDeDadosRoute: typeof ExclusaoDeDadosRoute
  ManutencaoRoute: typeof ManutencaoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  StatusRoute: typeof StatusRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-negado': {
      id: '/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof AcessoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consentimento': {
      id: '/consentimento'
      path: '/consentimento'
      fullPath: '/consentimento'
      preLoaderRoute: typeof ConsentimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusao-de-dados': {
      id: '/exclusao-de-dados'
      path: '/exclusao-de-dados'
      fullPath: '/exclusao-de-dados'
      preLoaderRoute: typeof ExclusaoDeDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/admin': {
      id: '/painel/admin'
      path: '/admin'
      fullPath: '/painel/admin'
      preLoaderRoute: typeof PainelAdminRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/campanhas': {
      id: '/painel/campanhas'
      path: '/campanhas'
      fullPath: '/painel/campanhas'
      preLoaderRoute: typeof PainelCampanhasRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/configuracoes': {
      id: '/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/integracoes': {
      id: '/painel/integracoes'
      path: '/integracoes'
      fullPath: '/painel/integracoes'
      preLoaderRoute: typeof PainelIntegracoesRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/leads': {
      id: '/painel/leads'
      path: '/leads'
      fullPath: '/painel/leads'
      preLoaderRoute: typeof PainelLeadsRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/listas': {
      id: '/painel/listas'
      path: '/listas'
      fullPath: '/painel/listas'
      preLoaderRoute: typeof PainelListasRouteImport
      parentRoute: typeof PainelRouteRoute
    }
  }
}

interface PainelRouteRouteChildren {
  PainelAdminRoute: typeof PainelAdminRoute
  PainelCampanhasRoute: typeof PainelCampanhasRoute
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelIntegracoesRoute: typeof PainelIntegracoesRoute
  PainelLeadsRoute: typeof PainelLeadsRoute
  PainelListasRoute: typeof PainelListasRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteRouteChildren: PainelRouteRouteChildren = {
  PainelAdminRoute: PainelAdminRoute,
  PainelCampanhasRoute: PainelCampanhasRoute,
  PainelConfiguracoesRoute: PainelConfiguracoesRoute,
  PainelIntegracoesRoute: PainelIntegracoesRoute,
  PainelLeadsRoute: PainelLeadsRoute,
  PainelListasRoute: PainelListasRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteRouteWithChildren = PainelRouteRoute._addFileChildren(
  PainelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRouteRoute: PainelRouteRouteWithChildren,
  AcessoNegadoRoute: AcessoNegadoRoute,
  CadastroRoute: CadastroRoute,
  ConsentimentoRoute: ConsentimentoRoute,
  CookiesRoute: CookiesRoute,
  EntrarRoute: EntrarRoute,
  ExclusaoDeDadosRoute: ExclusaoDeDadosRoute,
  ManutencaoRoute: ManutencaoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  StatusRoute: StatusRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
